### ISSUE TITLE
Question: best approach to get links to all POD documentation

### ISSUE THREAD

**Issue by skarfacegc** [CPAN-API/metacpan-client#28]
I'm working on writing a docset for [Dash.app](http://kapeli.com/dash) and I need to get a list of all of the modules that have pod documentation on metacpan.  Don't have enough code done yet to share, but my basic approach is this:

```
my $mcpan = MetaCPAN::Client->new();
my $all_modules = $mcpan->all( 'modules', { fields => [ "name", "module" ] } );

while ( $module = $all_modules->next )
 {
     my $mod_list = $module->module;
     next unless defined( $mod_list->[0]{name} );

      foreach my $mod ( @{$mod_list} )
      {
          HEAD request for metacpan.org/pod/$mod->{name} to check for existance
          
      } 
      pause 1/4 second for each 100 of these processed
}
```

write to database where appropriate etc.  Is there a better way to do this? 

Edit: Leaving the above in place for context.  I think the root of my problem/confusion is that it seems that I'm taking a fairly round-about path to do what I think would be a pretty common task: get a list of packages(?).
I'm not 100% sure I grok the relationship between module/file/package/release etc, which is likely why I'm asking this in the first place.  Anyway, is there a direct way to get a list of all things in cpan in the form "MetaCPAN::Client" or at least in a format where I can link to the pod documentation url.

**Comment by oalders** [comment]
@skarfacegc are you affiliated with this effort? https://github.com/CPAN-API/metacpan-web/issues/1114  (Just wondering).

As far as the relationships go, just think of modules as something you _might_ find inside of a file, where a file can contain 0, 1 or more modules.  MetaCPAN::Client deals with this by making the Module class a kind of alias to the File class.  So, if you just ask for all modules, you're likely going to get a lot of stuff you didn't _really_ want, since you're just getting a list of all files if you haven't provided any search constraints.

I wish I could say "just call this endpoint" to get what you need, but it's a little more complicated than that.  Since this is for Dash, you probably want the docs just for the latest, authorized versions of modules.  This example uses pure Elasticsearch, but it should essentially get you where you need to go:

https://github.com/CPAN-API/metacpan-examples/blob/master/scripts/endpoints/module/2-fetch-all-modules.pl

Really we should just have an endpoint which does this, but someone needs to add it first.  If you have any more questions, I'm happy to continue this discussion.  :)

**Comment by skarfacegc** [comment]
Nope I'm not involved.  :)  (though I'm about to post to that thread, thanks)

Thanks for the bit of code.  I haven't touched elastic search much yet.  Will be a good example to work from.

**Comment by oalders** [comment]
Great! To be clear, I'm not advocating using the Elasticsearch client for this query.  You can port it over to MetaCPAN::Client's DSL with little effort.

**Comment by skarfacegc** [comment]
I think I have it working now.  (pretty sure it's not as efficient as it could be)   I'm about 12 hours in on my first long run of the download, i suspect this will take somewhere around 20 hours or so to run.  My small tests seemed to work really well.

I hope I'm not querying too much from metacpan, I did set a UA and registered on the wiki page for folks using the API.

**Comment by skarfacegc** [comment]
Closing this as I think I have it working. Thanks @oalders

**Comment by oalders** [comment]
Thanks for following up. :+1:
